-- Rosaline Ecommerce Seed Data
-- Categories, Products, Users, Reviews, Blog Posts, Pages

-- Users
INSERT INTO `users` (`id`, `name`, `email`, `password`, `phone`, `role`, `created_at`, `updated_at`) VALUES
(1, 'Admin Rosaline', 'admin@rosaline.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '+1 (800) 555-2390', 'admin', NOW(), NOW()),
(2, 'Sarah Chen', 'sarah.chen@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '+1 (323) 555-0147', 'customer', NOW(), NOW()),
(3, 'Jessica Martinez', 'jessica.m@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '+1 (424) 555-0369', 'customer', NOW(), NOW());

-- Categories
INSERT INTO `categories` (`id`, `name`, `slug`, `description`, `image`, `parent_id`, `sort_order`, `created_at`, `updated_at`) VALUES
(1, 'Skincare', 'skincare', 'Clinical-grade cleansers, serums, moisturizers and treatments for every skin type.', 'assets/images/category/skincare.jpg', NULL, 1, NOW(), NOW()),
(2, 'Makeup', 'makeup', 'Clean, high-performance makeup that enhances your natural beauty.', 'assets/images/category/makeup.jpg', NULL, 2, NOW(), NOW()),
(3, 'Haircare', 'haircare', 'Nourishing shampoos, conditioners and treatments for healthy hair.', 'assets/images/category/haircare.jpg', NULL, 3, NOW(), NOW()),
(4, 'Fragrance', 'fragrance', 'Thoughtfully crafted scents that linger beautifully.', 'assets/images/category/fragrance.jpg', NULL, 4, NOW(), NOW()),
(5, 'Body Care', 'body-care', 'Luxurious body lotions, scrubs and oils for head-to-toe radiance.', 'assets/images/category/body-care.jpg', NULL, 5, NOW(), NOW()),
(6, 'Gifts & Sets', 'gifts-sets', 'Curated collections and gift sets for every occasion.', 'assets/images/category/gifts-sets.jpg', NULL, 6, NOW(), NOW()),
(7, 'Cleansers', 'cleansers', 'Gentle foaming, gel and oil cleansers.', 'assets/images/category/cleansers.jpg', 1, 1, NOW(), NOW()),
(8, 'Serums', 'serums', 'Targeted treatments with potent active ingredients.', 'assets/images/category/serums.jpg', 1, 2, NOW(), NOW()),
(9, 'Moisturizers', 'moisturizers', 'Lightweight creams and rich balms for lasting hydration.', 'assets/images/category/moisturizers.jpg', 1, 3, NOW(), NOW());

-- Products
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `description`, `short_description`, `price`, `compare_price`, `sku`, `stock_quantity`, `image`, `images`, `featured`, `status`, `created_at`, `updated_at`) VALUES
(1, 7, 'Hydra Glow Cleanser', 'hydra-glow-cleanser', 'A silky gel cleanser that removes impurities without stripping the skin. Formulated with amino-acid surfactants and niacinamide to gently cleanse while maintaining the skin barrier. Leaves skin feeling fresh, hydrated, and radiant.', 'Gentle gel cleanser with amino acids for dewy, balanced skin.', 28.00, 35.00, 'SKN-CLN-001', 150, 'assets/images/product/product-18.jpg', '[\"assets/images/product/product-18.jpg\", \"assets/images/product/product-18_2.jpg\"]', 1, 'active', NOW(), NOW()),
(2, 8, 'AHA Rosaline Serum 10%', 'aha-rosaline-serum-10', 'A powerhouse 10% AHA blend of glycolic, lactic and mandelic acids that resurfaces skin texture, fades dark spots, and unclogs pores. Formulated at a skin-balanced pH of 3.8 for maximum efficacy with minimal irritation.', 'Clinical 10% AHA blend. Resurfaces, brightens, refines texture.', 38.00, NULL, 'SKN-SRM-001', 200, 'assets/images/product/product-13.jpg', '[\"assets/images/product/product-13.jpg\", \"assets/images/product/product-13_2.jpg\"]', 1, 'active', NOW(), NOW()),
(3, 9, 'Barrier Repair Cream', 'barrier-repair-cream', 'A rich yet weightless moisturizer that strengthens the skin barrier with ceramides, squalane, and oat lipids. Clinically proven to improve hydration by 87% after one application. Suitable for even the most sensitive skin types.', 'Clinically proven 24-hour hydration. Strengthens skin barrier.', 42.00, NULL, 'SKN-MST-001', 90, 'assets/images/product/product-15.jpg', '[\"assets/images/product/product-15.jpg\", \"assets/images/product/product-15_2.jpg\"]', 1, 'active', NOW(), NOW()),
(4, 8, 'Vitamin C Brightening Serum 15%', 'vitamin-c-brightening-serum-15', 'A stabilized 15% L-ascorbic acid serum with ferulic acid and vitamin E. Brightens hyperpigmentation, boosts collagen production, and protects against oxidative stress. The gold standard for achieving luminous, even-toned skin.', 'Clinical grade 15% vitamin C. Brightens, firms, protects.', 54.00, 62.00, 'SKN-SRM-002', 120, 'assets/images/product/product-14.jpg', '[\"assets/images/product/product-14.jpg\", \"assets/images/product/product-14_2.jpg\"]', 1, 'active', NOW(), NOW()),
(5, 8, 'Niacinamide 5% + Zinc', 'niacinamide-5-zinc', 'A lightweight, fast-absorbing serum that reduces excess sebum production, minimizes enlarged pores, and calms inflammation. The 5% niacinamide concentration delivers visible results without irritation, suitable for daily use.', 'Reduces breakouts up to 90%. Minimizes pores, controls shine.', 26.00, NULL, 'SKN-SRM-003', 280, 'assets/images/product/product-22.jpg', '[\"assets/images/product/product-22.jpg\", \"assets/images/product/product-22_2.jpg\"]', 0, 'active', NOW(), NOW()),
(6, 7, 'Oil-to-Milk Cleansing Balm', 'oil-to-milk-cleansing-balm', 'A luxurious cleansing balm transforms from a silky oil into a milky emulsion. Dissolves waterproof makeup, SPF and excess sebum. Enriched with camellia oil and vitamin E to leave skin soft, never stripped.', 'Buttery balm melts away makeup and SPF without residue.', 32.00, NULL, 'SKN-CLN-002', 75, 'assets/images/product/product-14.jpg', '[\"assets/images/product/product-14.jpg\", \"assets/images/product/product-14_2.jpg\"]', 0, 'active', NOW(), NOW()),
(7, 2, 'LashLift Defining Mascara', 'lashlift-defining-mascara', 'A buildable, smudge-proof mascara that lengthens and curls with a clean formula. The precision wand coats every lash from root to tip. Free from parabens, phthalates and synthetic fragrances.', 'Clinically tested. +92% saw longer, defined lashes.', 24.00, 29.00, 'MUP-LSH-001', 90, 'assets/images/product/product-20.jpg', '[\"assets/images/product/product-20.jpg\", \"assets/images/product/product-20_2.jpg\"]', 0, 'active', NOW(), NOW()),
(8, 2, 'Hydra Shine Lip Gloss', 'hydra-shine-lip-gloss', 'A high-shine, non-sticky lip gloss infused with vitamin E and jojoba oil. Delivers a glass-like finish while conditioning lips. Available in six sheer shades from barely-there nude to rose petal.', 'Infused with vitamin E for smooth, glossy lips.', 38.00, 40.00, 'MUP-LIP-001', 95, 'assets/images/product/product-17.jpg', '[\"assets/images/product/product-17.jpg\", \"assets/images/product/product-17_2.jpg\"]', 1, 'active', NOW(), NOW()),
(9, 3, 'Repair & Restore Shampoo', 'repair-restore-shampoo', 'A sulfate-free shampoo with keratin, argan oil and biotin that gently cleanses while strengthening damaged hair. Restores elasticity, reduces breakage, and adds visible shine with every wash.', 'Sulfate-free repair shampoo with keratin and argan oil.', 28.00, NULL, 'HCR-SHP-001', 60, 'assets/images/product/product-21.jpg', '[\"assets/images/product/product-21.jpg\", \"assets/images/product/product-21_2.jpg\"]', 0, 'active', NOW(), NOW()),
(10, 4, 'Bloom Eau de Parfum', 'bloom-eau-de-parfum', 'An elegant floral fragrance with top notes of bergamot and pear, a heart of peony and rose, and a warm base of musk and sandalwood. Long-lasting yet delicate. Perfect for everyday luxury.', 'A delicate floral fragrance with peony, rose and warm musk.', 89.00, NULL, 'FRG-EDP-001', 40, 'assets/images/product/product-16.jpg', '[\"assets/images/product/product-16.jpg\", \"assets/images/product/product-16_2.jpg\"]', 1, 'active', NOW(), NOW()),
(11, 5, 'Velvet Body Crème', 'velvet-body-creme', 'An indulgent body crème with shea butter, cocoa butter and squalane that melts into skin for lasting softness. Rich enough for dry skin, yet absorbs without greasiness. Subtle warm vanilla scent.', 'Ultra-rich shea butter body crème for velvety soft skin.', 32.00, 38.00, 'BDY-CRM-001', 110, 'assets/images/product/product-22.jpg', '[\"assets/images/product/product-22.jpg\", \"assets/images/product/product-22_2.jpg\"]', 0, 'active', NOW(), NOW()),
(12, 6, 'The Essential Skincare Kit', 'essential-skincare-kit', 'Everything you need for a complete routine: Hydra Glow Cleanser, Niacinamide 5% + Zinc Serum, Barrier Repair Cream, and a luxe muslin cloth. Packaged in a reusable organic cotton gift bag. The perfect introduction to Rosaline.', 'Complete 3-piece starter routine. Full sizes plus gift bag.', 79.00, 96.00, 'GFT-KIT-001', 35, 'assets/images/product/product-18.jpg', '[\"assets/images/product/product-18.jpg\", \"assets/images/product/product-23.jpg\"]', 1, 'active', NOW(), NOW());

-- Reviews
INSERT INTO `reviews` (`id`, `product_id`, `user_id`, `rating`, `comment`, `status`, `created_at`) VALUES
(1, 2, 2, 5, 'I have been using this serum for three weeks and my skin texture has transformed. The fine lines around my eyes are visibly reduced and my complexion looks so much brighter. A holy grail product!', 'approved', NOW() - INTERVAL 14 DAY),
(2, 5, 3, 5, 'This niacinamide serum completely changed my skin. I struggled with hormonal breakouts for years and this is the first product that actually calms them down. Lightweight and layers beautifully under moisturizer.', 'approved', NOW() - INTERVAL 7 DAY),
(3, 8, 2, 4, 'Beautiful gloss with amazing shine. The rose shade is perfect for everyday wear. Only wish it lasted a bit longer, but the hydration is real.', 'approved', NOW() - INTERVAL 5 DAY),
(4, 10, 3, 5, 'This perfume is absolutely divine! I receive compliments everywhere I go. It smells elegant without being overpowering. Lasts about 6-7 hours on my skin.', 'approved', NOW() - INTERVAL 3 DAY);

-- Blog Posts
INSERT INTO `blog_posts` (`id`, `title`, `slug`, `content`, `excerpt`, `image`, `author`, `published_at`, `created_at`) VALUES
(1, 'Start Fresh: A Simple 3-Step Morning Skincare for Busy Days', 'morning-skincare-routine', '<p>Mornings can be hectic, but your skincare routine does not have to be complicated. A streamlined 3-step regimen can protect, hydrate, and prepare your skin for the day ahead without eating into your precious morning minutes.</p><h3>Step 1: Cleanse Gently</h3><p>Start with a gentle, non-stripping cleanser like our Hydra Glow Cleanser. Use lukewarm water and massage the cleanser in circular motions for 60 seconds. This removes overnight buildup while keeping your skin barrier intact.</p><h3>Step 2: Targeted Treatment</h3><p>Apply your Vitamin C Brightening Serum while skin is still slightly damp. The 15% L-ascorbic acid works best when applied before heavier products. A few drops pressed into the skin is all you need.</p><h3>Step 3: Moisturize + Protect</h3><p>Lock everything in with Barrier Repair Cream. Follow with SPF 50+ sunscreen — the single most important anti-aging step you can take.</p><p>That is it. Three steps, five minutes, and you are ready to take on the day with glowing skin.</p>', 'A simple, effective 3-step morning skincare routine for busy days. Cleanse, treat, moisturize and protect in under five minutes.', 'assets/images/blog/blog-1.jpg', 'Sarah Chen', '2025-09-14 08:00:00', NOW()),
(2, 'Niacinamide vs Vitamin C: Can You Use Them Together?', 'niacinamide-vs-vitamin-c', '<p>One of the most common questions we hear is whether niacinamide and vitamin C can be used together. The short answer: yes, absolutely — and your skin will thank you for it.</p><h3>The Old Myth</h3><p>An outdated study from the 1960s suggested that niacinamide and vitamin C could neutralize each other when mixed. This was based on a specific formulation condition that rarely applies to modern, well-formulated products.</p><h3>The Modern Reality</h3><p>Current dermatological research confirms that niacinamide and vitamin C are a powerhouse combination. Use your vitamin C serum in the morning and niacinamide in the evening for best results, or apply them together if your formulas are stabilized.</p><p>Together they address hyperpigmentation, textural concerns, barrier function, and environmental protection more effectively than either ingredient alone.</p>', 'Can niacinamide and vitamin C be used together? The answer is yes — here is how to layer them for maximum benefit.', 'assets/images/blog/blog-2.jpg', 'Dr. Elena Martinez', '2025-09-02 10:00:00', NOW()),
(3, 'The Ultimate Winter Skincare Survival Guide', 'winter-skincare-survival-guide', '<p>As temperatures drop and indoor heating kicks in, your skin faces increased moisture loss and barrier stress. Here is how to keep your complexion comfortable and glowing all winter long.</p><h3>Switch to a Creamier Cleanser</h3><p>If you use a gel or foaming cleanser in warmer months, consider swapping to our Oil-to-Milk Cleansing Balm. The lipid-rich formula removes impurities while replenishing moisture.</p><h3>Layer Your Hydration</h3><p>Apply your Niacinamide 5% + Zinc Serum onto damp skin, follow with Barrier Repair Cream, and seal with a facial oil if you need extra insulation. This sandwich technique locks in maximum hydration.</p><h3>Do Not Forget Your Body</h3><p>Your body needs attention too. Apply Velvet Body Crème immediately after showering while skin is still damp to trap moisture. Pay special attention to elbows, knees, and hands.</p>', 'Protect your skin from winter\'s harsh conditions with these expert tips on switching cleansers, layering hydration, and body care.', 'assets/images/blog/blog-3.jpg', 'Sarah Chen', '2025-11-20 09:00:00', NOW());

-- Pages
INSERT INTO `pages` (`id`, `title`, `slug`, `content`, `created_at`, `updated_at`) VALUES
(1, 'About Us', 'about', '<p>Founded in 2019 in Los Angeles, Rosaline was born from a simple belief: great skincare does not have to choose between efficacy and integrity. Our co-founders, Dr. Elena Martinez and Sarah Chen, set out to create a line of clinically proven formulas that respect both your skin and the planet.</p><p>Every product is developed in partnership with dermatologists and formulated without parabens, sulfates, phthalates, synthetic fragrances, or animal-derived ingredients. We test for results, not on animals. Our packaging is recyclable or refillable wherever possible.</p><p>Today, Rosaline is trusted by over 50,000 customers worldwide. Each product represents over 18 months of research and development, with rigorous clinical and performance testing before it reaches your shelf.</p><p>We believe in clean beauty that works — science-backed formulas that deliver visible results while honoring the skin you are in.</p>', NOW(), NOW()),
(2, 'Frequently Asked Questions', 'faq', '<h3>Shipping & Delivery</h3><p><strong>How long does shipping take?</strong> We offer free standard shipping on all orders over $49 within the continental US. Standard shipping takes 3-7 business days. Express shipping (2-3 business days) is available for $12.99.</p><p><strong>Do you ship internationally?</strong> Yes, we ship to over 40 countries worldwide. International shipping typically takes 7-14 business days and rates vary by destination.</p><h3>Returns & Exchanges</h3><p><strong>What is your return policy?</strong> We stand by our products. If you are not satisfied for any reason, you may return unused products within 30 days of delivery for a full refund.</p><p><strong>How do I start a return?</strong> Contact our support team at support@glowlyskin.com with your order number, and we will provide a prepaid return label.</p><h3>Ingredients & Safety</h3><p><strong>Are your products cruelty-free?</strong> Yes. Rosaline is certified cruelty-free by Leaping Bunny and PETA. We never test on animals.</p><p><strong>Are your products safe for sensitive skin?</strong> Our formulas are dermatologist-tested and designed with sensitive skin in mind. We always recommend patch testing any new product.</p>', NOW(), NOW()),
(3, 'Privacy Policy', 'privacy-policy', '<p>Last updated: January 1, 2026</p><p>Rosaline Skin LLC ("Rosaline," "we," "us," "our") respects your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information when you visit our website.</p><h3>Information We Collect</h3><p>We collect personal information you provide: name, email address, shipping address, billing information, and phone number. We also collect non-personal information through cookies and analytics, including browsing behavior, device type, and IP address.</p><h3>How We Use Your Information</h3><p>Your information is used to fulfill orders, send marketing communications (with your consent), improve our website and products, and comply with legal obligations.</p><h3>Your Rights</h3><p>You can access, update, or delete your personal data at any time through your account settings. You may unsubscribe from marketing emails at any time.</p><p>For questions, contact us at support@glowlyskin.com.</p>', NOW(), NOW()),
(4, 'Terms of Service', 'terms-of-service', '<p>Last updated: January 1, 2026</p><p>These Terms of Service govern your use of the Rosaline website and your purchase of products from Rosaline.</p><h3>Account Terms</h3><p>You must be at least 18 years old to create an account. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account.</p><h3>Pricing & Payment</h3><p>All prices are in USD unless otherwise noted. We reserve the right to modify prices at any time. Payment is due at the time of purchase.</p><h3>Shipping & Delivery</h3><p>We strive to process orders within 1-2 business days. Risk of loss passes to you upon delivery. You are responsible for providing accurate shipping information.</p><h3>Limitation of Liability</h3><p>Rosaline shall not be liable for any indirect, incidental, or consequential damages arising from the use of our products or website.</p><p>For questions, contact us at support@glowlyskin.com.</p>', NOW(), NOW());